// Texte von FUGE. Alles Allgemeine (Neu, Einstellungen …) kommt aus der Hülle.

export const FUGE_STRINGS = {
  de: {
    subtitle: 'Fallende Steine',
    boardLabel: 'Spielkasten',
    hold: 'Halten',
    pause: 'Pause',
    resume: 'Weiter',
    start: 'Start',
    modes: 'Modi',
    chooseMode: 'Modus wählen',
    coach: 'Hier wählst du den Modus',
    points: { one: 'Punkt', other: 'Punkte' },
    time: 'Zeit',
    mode: {
      classic: 'Klassisch',
      sprint: 'Sprint',
      ultra: '3 Minuten',
      calm: 'Ruhe',
    },
    modeMeta: {
      classic: 'Endlos, immer schneller',
      sprint: '40 Reihen auf Zeit',
      ultra: 'Punkte in drei Minuten',
      calm: 'Ohne Eile, ohne Ende',
    },
    best: 'Bestwert {v}',
    bestTime: 'Bestzeit {v}',
    side: {
      hold: 'Halten',
      next: 'Nächste',
      level: 'Stufe',
      lines: 'Reihen',
      pieces: 'Steine',
      left: 'Zeit',
    },
    ready: {
      touch: 'Tippen zum Starten',
      keys: 'Leertaste oder Klick zum Starten',
    },
    paused: {
      title: 'Pause',
      touch: 'Tippen zum Fortsetzen',
      keys: 'Leertaste oder Klick zum Fortsetzen',
    },
    help: {
      touch: [
        'Ziehen|verschieben',
        'Tippen|drehen, links ↺ rechts ↻',
        'Wischen ↓|fallen lassen',
        'Wischen ↑|halten',
      ],
      keys: [
        '← →|verschieben',
        '↑  X  Z|drehen',
        '↓|schneller fallen',
        'Leertaste|fallen lassen',
        'C|halten',
        'P|Pause',
      ],
    },
    clear: {
      1: 'Einzel',
      2: 'Doppel',
      3: 'Dreier',
      4: 'Quart',
    },
    tspin: 'T-Dreh',
    tspinMini: 'T-Dreh Mini',
    combo: 'Serie {n}',
    backToBack: 'Folge',
    perfect: 'Leer geräumt',
    levelUp: 'Stufe {n}',
    calmClear: 'Neu geordnet',
    over: {
      best: ['Neuer Bestwert', 'Der Kasten ist voll.'],
      plain: ['Gut gespielt', 'Der Kasten ist voll.'],
      sprintFail: ['Kasten voll', 'Noch {n} Reihen bis zum Ziel.'],
      sprintBest: ['Neue Bestzeit', '40 Reihen in {t}.'],
      sprintDone: ['Geschafft', '40 Reihen in {t}.'],
      ultraBest: ['Neuer Bestwert', '{n} Punkte in drei Minuten.'],
      ultraDone: ['Die Zeit ist um', '{n} Punkte in drei Minuten.'],
    },
    stat: {
      score: 'Punkte {v}',
      lines: 'Reihen {v}',
      level: 'Stufe {v}',
      time: 'Zeit {v}',
      pieces: 'Steine {v}',
      quarts: 'Quart {v}',
      best: 'Bestwert {v}',
      bestTime: 'Bestzeit {v}',
    },
    newGame: 'Neues Spiel',
    resumed: 'Dein Spiel geht weiter, wo du aufgehört hast.',
    ghost: 'Geisterstein',
    ghostText: 'Zeigt, wo der Stein landen wird',
    patterns: 'Muster auf den Steinen',
    patternsText: 'Jede Form trägt ein eigenes Zeichen, hilfreich bei Farbsehschwäche',
    note: 'Auf dem iPhone: Ziehen verschiebt, Tippen dreht, schnelles Wischen nach unten lässt fallen, nach oben hält. Am Rechner: Pfeiltasten, Leertaste, C und P.',
  },
  en: {
    subtitle: 'Falling blocks',
    boardLabel: 'Playing box',
    hold: 'Hold',
    pause: 'Pause',
    resume: 'Resume',
    start: 'Start',
    modes: 'Modes',
    chooseMode: 'Choose a mode',
    coach: 'Choose the mode here',
    points: { one: 'point', other: 'points' },
    time: 'Time',
    mode: {
      classic: 'Classic',
      sprint: 'Sprint',
      ultra: '3 minutes',
      calm: 'Calm',
    },
    modeMeta: {
      classic: 'Endless, ever faster',
      sprint: '40 lines against the clock',
      ultra: 'Score in three minutes',
      calm: 'No hurry, no end',
    },
    best: 'Best {v}',
    bestTime: 'Best time {v}',
    side: {
      hold: 'Hold',
      next: 'Next',
      level: 'Level',
      lines: 'Lines',
      pieces: 'Pieces',
      left: 'Time',
    },
    ready: {
      touch: 'Tap to start',
      keys: 'Press space or click to start',
    },
    paused: {
      title: 'Paused',
      touch: 'Tap to resume',
      keys: 'Press space or click to resume',
    },
    help: {
      touch: [
        'Drag|move',
        'Tap|rotate, left ↺ right ↻',
        'Swipe ↓|drop',
        'Swipe ↑|hold',
      ],
      keys: [
        '← →|move',
        '↑  X  Z|rotate',
        '↓|fall faster',
        'Space|drop',
        'C|hold',
        'P|pause',
      ],
    },
    clear: {
      1: 'Single',
      2: 'Double',
      3: 'Triple',
      4: 'Quart',
    },
    tspin: 'T-spin',
    tspinMini: 'T-spin mini',
    combo: 'Combo {n}',
    backToBack: 'Back to back',
    perfect: 'All clear',
    levelUp: 'Level {n}',
    calmClear: 'A fresh start',
    over: {
      best: ['New best', 'The box is full.'],
      plain: ['Well played', 'The box is full.'],
      sprintFail: ['Box full', '{n} lines to go.'],
      sprintBest: ['New best time', '40 lines in {t}.'],
      sprintDone: ['Done', '40 lines in {t}.'],
      ultraBest: ['New best', '{n} points in three minutes.'],
      ultraDone: ['Time is up', '{n} points in three minutes.'],
    },
    stat: {
      score: 'Score {v}',
      lines: 'Lines {v}',
      level: 'Level {v}',
      time: 'Time {v}',
      pieces: 'Pieces {v}',
      quarts: 'Quarts {v}',
      best: 'Best {v}',
      bestTime: 'Best time {v}',
    },
    newGame: 'New game',
    resumed: 'Your game continues where you left off.',
    ghost: 'Ghost piece',
    ghostText: 'Shows where the piece will land',
    patterns: 'Patterns on the pieces',
    patternsText: 'Each shape carries its own mark, helpful for colour blindness',
    note: 'On iPhone: drag to move, tap to rotate, swipe down quickly to drop, up to hold. On a computer: arrow keys, space, C and P.',
  },
};
