// Texte von QUEEN. Alles Allgemeine (Zurück, Neu, Einstellungen …) kommt aus der Hülle.

export const QUEEN_STRINGS = {
  de: {
    subtitle: 'Dame',
    boardLabel: 'Damebrett',
    modes: 'Modi',
    chooseMode: 'Modus wählen',
    coach: 'Hier wählst du den Modus',
    mode: {
      beginner: 'Einsteiger',
      easy: 'Leicht',
      medium: 'Mittel',
      hard: 'Schwer',
      duo: 'Zu zweit',
    },
    modeLabel: {
      beginner: 'Computer · Einsteiger',
      easy: 'Computer · Leicht',
      medium: 'Computer · Mittel',
      hard: 'Computer · Schwer',
      duo: 'Zu zweit',
    },
    vsComputer: 'Computer',
    onOneDevice: 'Ein Gerät',
    side: { blue: 'Blau', white: 'Weiß', black: 'Schwarz' },
    turn: '{side} zieht',
    thinkingTurn: '{side} denkt',
    over: 'Spiel beendet',
    won: ['Gewonnen', 'Du hast Schwarz bezwungen.'],
    lost: ['Verloren', 'Schwarz war diesmal stärker.'],
    sideWins: ['{side} gewinnt', '{side} kann nicht mehr ziehen.'],
    resigned: ['{side} gewinnt', '{side} hat aufgegeben.'],
    resignTitle: 'Partie aufgeben?',
    resignText: 'Das zählt als Niederlage. Mit Zurück kannst du es rückgängig machen.',
    resignTextDuo: '{side} gibt auf, {other} gewinnt.',
    draw: ['Remis', 'Keine Seite kommt mehr voran.'],
    drawRepetition: 'Dreimal dieselbe Stellung.',
    drawQuiet: '30 Halbzüge nur mit Damen ohne Schlag.',
    wins: { one: '{n} Sieg', other: '{n} Siege' },
    nextLevel: 'Nächste Stufe',
    noHint: 'Gerade kein Tipp verfügbar.',
    theme: 'Brett',
    themes: { classic: 'Klassik', midnight: 'Mitternacht' },
    flip: 'Brett drehen',
    flipText: 'Beim Spiel zu zweit dreht sich das Brett nach jedem Zug zur Person am Zug',
    tilt: 'Neigen',
    tiltText: 'Geschlagene Steine rutschen in der Schale, wenn du das Gerät neigst',
    tiltDenied: 'Zugriff auf den Bewegungssensor wurde nicht erlaubt.',
    tiltUnsupported: 'Dieses Gerät hat keinen Bewegungssensor.',
    trayHint: 'Tipp: Wische über die Steine in den Schalen.',
  },
  en: {
    subtitle: 'Checkers',
    boardLabel: 'Checkerboard',
    modes: 'Modes',
    chooseMode: 'Choose a mode',
    coach: 'Choose the mode here',
    mode: {
      beginner: 'Beginner',
      easy: 'Easy',
      medium: 'Medium',
      hard: 'Hard',
      duo: 'Two players',
    },
    modeLabel: {
      beginner: 'Computer · Beginner',
      easy: 'Computer · Easy',
      medium: 'Computer · Medium',
      hard: 'Computer · Hard',
      duo: 'Two players',
    },
    vsComputer: 'Computer',
    onOneDevice: 'One device',
    side: { blue: 'Blue', white: 'White', black: 'Black' },
    turn: '{side} moves',
    thinkingTurn: '{side} thinks',
    over: 'Game over',
    won: ['You win', 'You have beaten Black.'],
    lost: ['You lose', 'Black was stronger this time.'],
    sideWins: ['{side} wins', '{side} has no moves left.'],
    resigned: ['{side} wins', '{side} resigned.'],
    resignTitle: 'Resign this game?',
    resignText: 'It counts as a loss. Undo takes it back.',
    resignTextDuo: '{side} resigns, {other} wins.',
    draw: ['Draw', 'Neither side can make progress.'],
    drawRepetition: 'The same position three times.',
    drawQuiet: '30 moves with queens only and no capture.',
    wins: { one: '{n} win', other: '{n} wins' },
    nextLevel: 'Next level',
    noHint: 'No hint available right now.',
    theme: 'Board',
    themes: { classic: 'Classic', midnight: 'Midnight' },
    flip: 'Turn the board',
    flipText: 'With two players the board turns towards the player to move after every move',
    tilt: 'Tilt',
    tiltText: 'Captured pieces slide in their tray when you tilt your device',
    tiltDenied: 'Access to the motion sensor was not allowed.',
    tiltUnsupported: 'This device has no motion sensor.',
    trayHint: 'Tip: swipe across the pieces in the trays.',
  },
};
