// Texte von QUEEN. Alles Allgemeine (Zurück, Neu, Einstellungen …) kommt aus der Hülle.

export const QUEEN_STRINGS = {
  de: {
    subtitle: 'Dame',
    boardLabel: 'Damebrett',
    modes: 'Modi',
    chooseMode: 'Modus wählen',
    coach: 'Hier wählst du den Modus',
    mode: {
      easy: 'Leicht',
      medium: 'Mittel',
      hard: 'Schwer',
      duo: 'Zu zweit',
    },
    modeLabel: {
      easy: 'Computer · Leicht',
      medium: 'Computer · Mittel',
      hard: 'Computer · Schwer',
      duo: 'Zu zweit',
    },
    vsComputer: 'Computer',
    onOneDevice: 'Ein Gerät',
    turn: { blue: 'Blau zieht', black: 'Schwarz zieht' },
    thinkingTurn: 'Schwarz denkt',
    over: 'Spiel beendet',
    won: ['Gewonnen', 'Du hast Schwarz bezwungen.'],
    lost: ['Verloren', 'Schwarz war diesmal stärker.'],
    blueWins: ['Blau gewinnt', 'Schwarz kann nicht mehr ziehen.'],
    blackWins: ['Schwarz gewinnt', 'Blau kann nicht mehr ziehen.'],
    draw: ['Remis', 'Keine Seite kommt mehr voran.'],
    drawRepetition: 'Dreimal dieselbe Stellung.',
    drawQuiet: '30 Halbzüge nur mit Damen ohne Schlag.',
    wins: { one: '{n} Sieg', other: '{n} Siege' },
    nextLevel: 'Nächste Stufe',
    noHint: 'Gerade kein Tipp verfügbar.',
    flip: 'Brett drehen',
    flipText: 'Beim Spiel zu zweit dreht sich das Brett nach jedem Zug zur Person am Zug',
    tilt: 'Neigen',
    tiltText: 'Geschlagene Steine rutschen in der Schale, wenn du das Gerät neigst',
    tiltDenied: 'Zugriff auf den Bewegungssensor wurde nicht erlaubt.',
    tiltUnsupported: 'Dieses Gerät hat keinen Bewegungssensor.',
    trayHint: 'Tipp: Wische über die Steine in den Schalen.',
  },
  en: {
    subtitle: 'Checkers',
    boardLabel: 'Checkerboard',
    modes: 'Modes',
    chooseMode: 'Choose a mode',
    coach: 'Choose the mode here',
    mode: {
      easy: 'Easy',
      medium: 'Medium',
      hard: 'Hard',
      duo: 'Two players',
    },
    modeLabel: {
      easy: 'Computer · Easy',
      medium: 'Computer · Medium',
      hard: 'Computer · Hard',
      duo: 'Two players',
    },
    vsComputer: 'Computer',
    onOneDevice: 'One device',
    turn: { blue: 'Blue moves', black: 'Black moves' },
    thinkingTurn: 'Black thinks',
    over: 'Game over',
    won: ['You win', 'You have beaten Black.'],
    lost: ['You lose', 'Black was stronger this time.'],
    blueWins: ['Blue wins', 'Black has no moves left.'],
    blackWins: ['Black wins', 'Blue has no moves left.'],
    draw: ['Draw', 'Neither side can make progress.'],
    drawRepetition: 'The same position three times.',
    drawQuiet: '30 moves with queens only and no capture.',
    wins: { one: '{n} win', other: '{n} wins' },
    nextLevel: 'Next level',
    noHint: 'No hint available right now.',
    flip: 'Turn the board',
    flipText: 'With two players the board turns towards the player to move after every move',
    tilt: 'Tilt',
    tiltText: 'Captured pieces slide in their tray when you tilt your device',
    tiltDenied: 'Access to the motion sensor was not allowed.',
    tiltUnsupported: 'This device has no motion sensor.',
    trayHint: 'Tip: swipe across the pieces in the trays.',
  },
};
