// Texte von BLOCKS. Alles Allgemeine (Zurück, Tipp, Neu, Einstellungen …) kommt aus der Hülle.

export const BLOCKS_STRINGS = {
  de: {
    subtitle: 'Block-Puzzle',
    boardLabel: 'Spielbrett mit Tablett',
    modes: 'Modi',
    chooseMode: 'Modus wählen',
    coach: 'Hier wählst du den Modus',
    otherMode: 'Anderer Modus',
    points: { one: 'Punkt', other: 'Punkte' },
    mode: {
      classic: 'Klassisch',
      wide: 'Weit',
      calm: 'Ruhe',
    },
    modeMeta: {
      classic: '8 × 8, bis nichts mehr passt',
      wide: '10 × 10, mehr Platz',
      calm: 'Ohne Ende, alles passt',
    },
    best: 'Bestwert {v}',
    head: {
      best: 'Bestwert',
      streak: 'Serie',
    },
    lines: {
      2: 'Doppel',
      3: 'Dreifach',
      4: 'Vierfach',
      many: '{n} Linien',
    },
    streak: 'Serie {n}',
    perfect: 'Leer geräumt',
    calmClear: 'Neu geordnet',
    over: {
      best: ['Neuer Bestwert', 'Kein Stein passt mehr.'],
      plain: ['Gut gespielt', 'Kein Stein passt mehr.'],
    },
    stat: {
      score: 'Punkte {v}',
      lines: 'Linien {v}',
      pieces: 'Steine {v}',
      streak: 'Beste Serie {v}',
      best: 'Bestwert {v}',
    },
    noHint: 'Kein Stein passt mehr.',
    nothingToUndo: 'Nichts zurückzunehmen.',
    resumed: 'Dein Spiel geht weiter, wo du aufgehört hast.',
    preview: 'Linien vorab zeigen',
    previewText: 'Beim Ziehen leuchten Reihen und Spalten auf, die verschwinden würden',
    note: 'Ziehe die Steine vom Tablett aufs Brett. Volle Reihen und Spalten verschwinden. Am Rechner: 1, 2, 3 wählen, Pfeile schieben, Enter legt.',
  },
  en: {
    subtitle: 'Block puzzle',
    boardLabel: 'Board with tray',
    modes: 'Modes',
    chooseMode: 'Choose a mode',
    coach: 'Choose the mode here',
    otherMode: 'Other mode',
    points: { one: 'point', other: 'points' },
    mode: {
      classic: 'Classic',
      wide: 'Wide',
      calm: 'Calm',
    },
    modeMeta: {
      classic: '8 × 8, until nothing fits',
      wide: '10 × 10, more room',
      calm: 'No end, everything fits',
    },
    best: 'Best {v}',
    head: {
      best: 'Best',
      streak: 'Streak',
    },
    lines: {
      2: 'Double',
      3: 'Triple',
      4: 'Quadruple',
      many: '{n} lines',
    },
    streak: 'Streak {n}',
    perfect: 'All clear',
    calmClear: 'A fresh start',
    over: {
      best: ['New best', 'No piece fits any more.'],
      plain: ['Well played', 'No piece fits any more.'],
    },
    stat: {
      score: 'Score {v}',
      lines: 'Lines {v}',
      pieces: 'Pieces {v}',
      streak: 'Best streak {v}',
      best: 'Best {v}',
    },
    noHint: 'No piece fits any more.',
    nothingToUndo: 'Nothing to undo.',
    resumed: 'Your game continues where you left off.',
    preview: 'Show lines in advance',
    previewText: 'While dragging, rows and columns that would clear light up',
    note: 'Drag the pieces from the tray onto the board. Full rows and columns clear. On a computer: 1, 2, 3 to choose, arrows to move, Enter to place.',
  },
};
