// Texte von BLOCKS. Alles Allgemeine (Zurück, Tipp, Neu, Einstellungen …) kommt aus der Hülle.

export const BLOCKS_STRINGS = {
  de: {
    subtitle: 'Block-Puzzle',
    boardLabel: 'Spielbrett mit Tablett',
    levelsButton: 'Level',
    chooseLevel: 'Level und Modi',
    coach: 'Hier wählst du Level und Modi',
    nextLevel: 'Weiter',
    otherLevel: 'Anderes Level',
    levelName: 'Level {n}',
    levelMeta: 'Ziel {v} Punkte',
    lockedMeta: 'Noch gesperrt',
    locked: 'Schaffe zuerst Level {n}.',
    levelDone: {
      title: 'Level {n} geschafft',
      text1: 'Mit weniger Steinen gibt es mehr Sterne.',
      text2: 'Fast perfekt. Mit weniger Steinen gibt es drei Sterne.',
      text3: 'Perfekt gelöst.',
      last: 'Du hast alle 30 Level geschafft.',
    },
    levelFail: ['Kein Stein passt mehr', 'Level {n} ist noch nicht geschafft. Versuch es nochmal.'],
    goal: {
      short: 'Ziel {a} von {b}',
    },
    points: { one: 'Punkt', other: 'Punkte' },
    mode: {
      classic: 'Klassisch',
      wide: 'Weit',
      calm: 'Ruhe',
    },
    modeMeta: {
      classic: '8 × 8, bis nichts mehr passt',
      wide: '10 × 10, mehr Platz',
      calm: 'Ohne Ende, alles passt',
    },
    best: 'Bestwert {v}',
    head: {
      best: 'Bestwert',
      goal: 'Ziel',
      streak: 'Serie',
    },
    lines: {
      2: 'Doppel',
      3: 'Dreifach',
      4: 'Vierfach',
      many: '{n} Linien',
    },
    streak: 'Serie {n}',
    perfect: 'Leer geräumt',
    calmClear: 'Neu geordnet',
    over: {
      best: ['Neuer Bestwert', 'Kein Stein passt mehr.'],
      plain: ['Gut gespielt', 'Kein Stein passt mehr.'],
    },
    stat: {
      score: 'Punkte {v}',
      lines: 'Linien {v}',
      pieces: 'Steine {v}',
      streak: 'Beste Serie {v}',
      best: 'Bestwert {v}',
      par: 'Drei Sterne mit {v} Steinen',
      preLeft: 'Startsteine übrig {v}',
    },
    noHint: 'Kein Stein passt mehr.',
    nothingToUndo: 'Nichts zurückzunehmen.',
    resumed: 'Dein Spiel geht weiter, wo du aufgehört hast.',
    preview: 'Linien vorab zeigen',
    previewText: 'Beim Ziehen leuchten Reihen und Spalten auf, die verschwinden würden',
    note: 'Ziehe die Steine vom Tablett aufs Brett. Volle Reihen und Spalten verschwinden. Im Level räumst du alle schwarzen Startsteine ab und erreichst das Punkteziel. Am Rechner: 1, 2, 3 wählen, Pfeile schieben, Enter legt.',
  },
  en: {
    subtitle: 'Block puzzle',
    boardLabel: 'Board with tray',
    levelsButton: 'Levels',
    chooseLevel: 'Levels and modes',
    coach: 'Choose levels and modes here',
    nextLevel: 'Next level',
    otherLevel: 'Other level',
    levelName: 'Level {n}',
    levelMeta: 'Goal {v} points',
    lockedMeta: 'Still locked',
    locked: 'Complete level {n} first.',
    levelDone: {
      title: 'Level {n} complete',
      text1: 'Fewer pieces earn more stars.',
      text2: 'Almost perfect. Fewer pieces earn three stars.',
      text3: 'Solved perfectly.',
      last: 'You have completed all 30 levels.',
    },
    levelFail: ['No piece fits any more', 'Level {n} is not complete yet. Give it another try.'],
    goal: {
      short: 'Goal {a} of {b}',
    },
    points: { one: 'point', other: 'points' },
    mode: {
      classic: 'Classic',
      wide: 'Wide',
      calm: 'Calm',
    },
    modeMeta: {
      classic: '8 × 8, until nothing fits',
      wide: '10 × 10, more room',
      calm: 'No end, everything fits',
    },
    best: 'Best {v}',
    head: {
      best: 'Best',
      goal: 'Goal',
      streak: 'Streak',
    },
    lines: {
      2: 'Double',
      3: 'Triple',
      4: 'Quadruple',
      many: '{n} lines',
    },
    streak: 'Streak {n}',
    perfect: 'All clear',
    calmClear: 'A fresh start',
    over: {
      best: ['New best', 'No piece fits any more.'],
      plain: ['Well played', 'No piece fits any more.'],
    },
    stat: {
      score: 'Score {v}',
      lines: 'Lines {v}',
      pieces: 'Pieces {v}',
      streak: 'Best streak {v}',
      best: 'Best {v}',
      par: 'Three stars with {v} pieces',
      preLeft: 'Starting blocks left {v}',
    },
    noHint: 'No piece fits any more.',
    nothingToUndo: 'Nothing to undo.',
    resumed: 'Your game continues where you left off.',
    preview: 'Show lines in advance',
    previewText: 'While dragging, rows and columns that would clear light up',
    note: 'Drag the pieces from the tray onto the board. Full rows and columns clear. In a level, clear all black starting blocks and reach the points goal. On a computer: 1, 2, 3 to choose, arrows to move, Enter to place.',
  },
};
