// Texte von KARO. Alles Allgemeine (Zurück, Neu, Einstellungen …) kommt aus der Hülle.

export const KARO_STRINGS = {
  de: {
    subtitle: 'Patience',
    boardLabel: 'Spieltisch',
    points: { one: 'Punkt', other: 'Punkte' },
    vegas: 'Vegas',
    levels: 'Stufen',
    chooseLevel: 'Stufe wählen',
    nextDeal: 'Nächstes Spiel',
    coach: 'Hier wählst du die Stufe',
    level: {
      easy: 'Leicht',
      medium: 'Mittel',
      hard: 'Schwer',
      master: 'Meisterhaft',
      daily: 'Tagesspiel',
      random: 'Zufall',
    },
    levelMeta: {
      easy: 'Ein klarer Weg',
      medium: 'Etwas Planung',
      hard: 'Vorausdenken',
      master: 'Ein schmaler Pfad',
      daily: 'Für alle gleich, jeden Tag neu',
      random: 'Ohne Garantie',
    },
    cards: { one: '{n} Karte', other: '{n} Karten' },
    dealNo: 'Spiel Nr. {n}',
    draw3: 'Drei Karten ziehen',
    draw3Text: 'Schwerer: Nur die oberste von drei gezogenen Karten ist spielbar',
    vegasMode: 'Vegas',
    vegasText: '52 Einsatz, 5 für jede Karte auf einer Ablage, begrenzte Durchgänge',
    rulesChanged: 'Neues Spiel mit den neuen Regeln. Mit Zurück holst du das alte zurück.',
    noRecycle: 'Keine Durchgänge mehr.',
    passesLeft: { one: 'Noch {n} Durchgang', other: 'Noch {n} Durchgänge' },
    noSolution: 'Von hier aus geht es nicht mehr auf. Nimm ein paar Züge zurück.',
    hintTimeout: 'Gerade kein Tipp gefunden. Versuch es nach dem nächsten Zug noch einmal.',
    hintDraw: 'Zieh eine Karte vom Stapel.',
    stuck: ['Keine Züge mehr', 'Nimm Züge zurück oder starte ein neues Spiel.'],
    wasSolvable: 'Dieses Spiel wäre lösbar gewesen.',
    wasUnsolvable: 'Dieses Spiel war nicht zu gewinnen. Das lag nicht an dir.',
    rating: {
      perfect: ['Makellos', 'Gelöst ohne Zurück und ohne Tipp.'],
      good: ['Sehr gut', 'Gelöst ohne Tipp.'],
      solved: ['Gelöst', 'Alle Karten liegen auf den Ablagen.'],
    },
    stat: {
      score: 'Punkte: {n}',
      bonus: 'Zeitbonus: {n}',
      time: 'Zeit: {t}',
      moves: 'Züge: {n}',
      bank: 'Vegas-Konto: {n}',
      won: 'Gewonnen: {n} von {m}',
    },
    note: 'Tipp: Tippe eine Karte an, sie springt an den besten Platz. Ziehen geht auch. Jede Stufe außer Zufall ist sicher lösbar.',
  },
  en: {
    subtitle: 'Solitaire',
    boardLabel: 'Card table',
    points: { one: 'point', other: 'points' },
    vegas: 'Vegas',
    levels: 'Levels',
    chooseLevel: 'Choose a level',
    nextDeal: 'Next deal',
    coach: 'Choose the level here',
    level: {
      easy: 'Easy',
      medium: 'Medium',
      hard: 'Hard',
      master: 'Masterful',
      daily: 'Daily deal',
      random: 'Random',
    },
    levelMeta: {
      easy: 'A clear path',
      medium: 'Some planning',
      hard: 'Think ahead',
      master: 'A narrow path',
      daily: 'Same for everyone, new each day',
      random: 'No guarantee',
    },
    cards: { one: '{n} card', other: '{n} cards' },
    dealNo: 'Deal no. {n}',
    draw3: 'Draw three',
    draw3Text: 'Harder: only the top one of three drawn cards is playable',
    vegasMode: 'Vegas',
    vegasText: '52 stake, 5 for every card on a foundation, limited passes',
    rulesChanged: 'New game with the new rules. Tap Undo to get the previous one back.',
    noRecycle: 'No passes left.',
    passesLeft: { one: '{n} pass left', other: '{n} passes left' },
    noSolution: 'From here it can no longer be solved. Undo a few moves.',
    hintTimeout: 'No hint found right now. Try again after your next move.',
    hintDraw: 'Draw a card from the stock.',
    stuck: ['No moves left', 'Undo a few moves or start a new game.'],
    wasSolvable: 'This deal could have been solved.',
    wasUnsolvable: 'This deal could not be won. It was not down to you.',
    rating: {
      perfect: ['Flawless', 'Solved without undo and without hints.'],
      good: ['Excellent', 'Solved without hints.'],
      solved: ['Solved', 'Every card is on the foundations.'],
    },
    stat: {
      score: 'Score: {n}',
      bonus: 'Time bonus: {n}',
      time: 'Time: {t}',
      moves: 'Moves: {n}',
      bank: 'Vegas bank: {n}',
      won: 'Won: {n} of {m}',
    },
    note: 'Tip: tap a card and it jumps to the best place. Dragging works too. Every level except Random can be solved.',
  },
};
