// Texte von MÜHLE. Alles Allgemeine (Zurück, Neu, Einstellungen …) kommt aus der Hülle.

export const MUEHLE_STRINGS = {
  de: {
    subtitle: 'Mühle',
    boardLabel: 'Mühlebrett',
    modes: 'Modi',
    chooseMode: 'Modus wählen',
    coach: 'Hier wählst du den Modus',
    otherMode: 'Anderer Modus',
    mode: {
      easy: 'Leicht',
      medium: 'Mittel',
      hard: 'Schwer',
      duo: 'Zu zweit',
    },
    modeLabel: {
      easy: 'Computer · Leicht',
      medium: 'Computer · Mittel',
      hard: 'Computer · Schwer',
      duo: 'Zu zweit',
    },
    vsComputer: 'Computer',
    onOneDevice: 'Ein Gerät',
    side: { blue: 'Blau', white: 'Weiß', black: 'Schwarz' },
    phase: {
      place: '{side} setzt',
      move: '{side} zieht',
      fly: '{side} springt',
    },
    removeTurn: '{side} nimmt',
    thinkingTurn: '{side} denkt',
    over: 'Spiel beendet',
    won: ['Gewonnen', 'Du hast Schwarz bezwungen.'],
    lost: ['Verloren', 'Schwarz war diesmal stärker.'],
    sideWins: '{side} gewinnt',
    reason: {
      few: '{side} hat nur noch zwei Steine.',
      blocked: '{side} kann nicht mehr ziehen.',
    },
    draw: ['Remis', 'Keine Seite kommt mehr voran.'],
    drawRepetition: 'Dreimal dieselbe Stellung.',
    drawQuiet: '20 Züge je Seite ohne Mühle.',
    millToast: 'Mühle! Tippe auf einen Stein, den du nehmen willst.',
    wins: { one: '{n} Sieg', other: '{n} Siege' },
    nextLevel: 'Nächste Stufe',
    noHint: 'Gerade kein Tipp verfügbar.',
    theme: 'Brett',
    themes: { classic: 'Klassik', midnight: 'Mitternacht' },
    flip: 'Brett drehen',
    flipText: 'Beim Spiel zu zweit dreht sich das Brett nach jedem Zug zur Person am Zug',
    tilt: 'Neigen',
    tiltText: 'Die Steine in den Schalen rutschen, wenn du das Gerät neigst',
    tiltDenied: 'Zugriff auf den Bewegungssensor wurde nicht erlaubt.',
    tiltUnsupported: 'Dieses Gerät hat keinen Bewegungssensor.',
    trayHint: 'Tipp: In deiner Schale liegen deine Steine zum Setzen und die Steine, die du genommen hast. Wische darüber.',
  },
  en: {
    subtitle: "Nine Men's Morris",
    boardLabel: 'Morris board',
    modes: 'Modes',
    chooseMode: 'Choose a mode',
    coach: 'Choose the mode here',
    otherMode: 'Other mode',
    mode: {
      easy: 'Easy',
      medium: 'Medium',
      hard: 'Hard',
      duo: 'Two players',
    },
    modeLabel: {
      easy: 'Computer · Easy',
      medium: 'Computer · Medium',
      hard: 'Computer · Hard',
      duo: 'Two players',
    },
    vsComputer: 'Computer',
    onOneDevice: 'One device',
    side: { blue: 'Blue', white: 'White', black: 'Black' },
    phase: {
      place: '{side} places',
      move: '{side} moves',
      fly: '{side} flies',
    },
    removeTurn: '{side} takes',
    thinkingTurn: '{side} thinks',
    over: 'Game over',
    won: ['You win', 'You have beaten Black.'],
    lost: ['You lose', 'Black was stronger this time.'],
    sideWins: '{side} wins',
    reason: {
      few: '{side} has only two pieces left.',
      blocked: '{side} has no moves left.',
    },
    draw: ['Draw', 'Neither side can make progress.'],
    drawRepetition: 'The same position three times.',
    drawQuiet: '20 moves each without a mill.',
    millToast: 'Mill! Tap the piece you want to take.',
    wins: { one: '{n} win', other: '{n} wins' },
    nextLevel: 'Next level',
    noHint: 'No hint available right now.',
    theme: 'Board',
    themes: { classic: 'Classic', midnight: 'Midnight' },
    flip: 'Turn the board',
    flipText: 'With two players the board turns towards the player to move after every move',
    tilt: 'Tilt',
    tiltText: 'The pieces in the trays slide when you tilt your device',
    tiltDenied: 'Access to the motion sensor was not allowed.',
    tiltUnsupported: 'This device has no motion sensor.',
    trayHint: 'Tip: your tray holds the pieces you still have to place and the pieces you have taken. Swipe across them.',
  },
};
