// Texte von SPRING. Alles Allgemeine (Zurück, Neu, Einstellungen …) kommt aus der Hülle.

export const SPRING_STRINGS = {
  de: {
    subtitle: 'Solohalma',
    boardLabel: 'Spielbrett',
    marbles: { one: 'Murmel', other: 'Murmeln' },
    figures: 'Figuren',
    chooseFigure: 'Figur wählen',
    coach: 'Hier wechselst du die Figur',
    otherFigure: 'Andere Figur',
    rating: {
      perfect: ['Meisterhaft', 'Eine Murmel, genau in der Mitte.'],
      one: ['Sehr gut', 'Nur noch eine Murmel übrig.'],
      two: ['Gut', 'Zwei Murmeln übrig.'],
      three: ['Ordentlich', 'Drei Murmeln übrig.'],
      more: ['Weiter üben', '{n} Murmeln übrig.'],
    },
    best: { one: 'Bestes Ergebnis: {n} Murmel', other: 'Bestes Ergebnis: {n} Murmeln' },
    solved: 'Gelöst: {n}×',
    nextFigure: 'Nächste Figur',
    noSolution: 'Von hier aus geht es nicht mehr perfekt auf. Nimm ein paar Züge zurück.',
    hintTimeout: 'Gerade kein Tipp gefunden. Versuch es nach dem nächsten Zug noch einmal.',
    tilt: 'Neigen',
    tiltText: 'Murmeln im Rand rollen, wenn du das Gerät neigst',
    tiltDenied: 'Zugriff auf den Bewegungssensor wurde nicht erlaubt.',
    tiltUnsupported: 'Dieses Gerät hat keinen Bewegungssensor.',
    rimHint: 'Tipp: Wische über die Murmeln im Rand.',
  },
  en: {
    subtitle: 'Peg Solitaire',
    boardLabel: 'Game board',
    marbles: { one: 'marble', other: 'marbles' },
    figures: 'Figures',
    chooseFigure: 'Choose a figure',
    coach: 'Change the figure here',
    otherFigure: 'Other figure',
    rating: {
      perfect: ['Masterful', 'One marble, right in the centre.'],
      one: ['Excellent', 'Only one marble left.'],
      two: ['Good', 'Two marbles left.'],
      three: ['Decent', 'Three marbles left.'],
      more: ['Keep practising', '{n} marbles left.'],
    },
    best: { one: 'Best result: {n} marble', other: 'Best result: {n} marbles' },
    solved: 'Solved: {n}×',
    nextFigure: 'Next figure',
    noSolution: 'From here a perfect finish is no longer possible. Undo a few moves.',
    hintTimeout: 'No hint found right now. Try again after your next move.',
    tilt: 'Tilt',
    tiltText: 'Marbles in the rim roll when you tilt your device',
    tiltDenied: 'Access to the motion sensor was not allowed.',
    tiltUnsupported: 'This device has no motion sensor.',
    rimHint: 'Tip: swipe across the marbles in the rim.',
  },
};
